### ISSUE TITLE
hashrate drops to zero after an about hour of mining

### ISSUE THREAD

**Issue by tinsami1** [MoneroOcean/xmrig-amd#4]
Happened in two consecutive runs.

xmrig-amd switches several times between cn/msr and cnh/tube.  Then hashrate then drops to zero after about an hour.  In both cases, cn-heavy/tube was being mined.

In the second run, I noticed that:
(a)  before the last switch from MSR to TUBE, one of the two GPUs were mining only at 64% gpu utilization -- I guess only 1 or 2 threads was running.
(b)  that the drop occured a few seconds after switching from MSR to TUBE.
(c)  there was a notification in Windows 10 that the program was disallowed from accessing the gpu (sorry, can't recall the exact words).

**Comment by tinsami1** [comment]
So... I lowered the algo-perf figure for cn-heavy to less than half of the calibration result. Xmrig-amd has been running for 4 hours now without hashrate drop. It hasn’t switched to/from cn-heavy yet.

**Comment by setuidroot** [comment]
This is/was likely caused by you having too high of an intensity setting for cn-heavy in config.json.  The autoconfig setting sets it too high in my experience and that can cause GPUs to crash when they run out of memory.  Your intensity settings for cn-heavy should probably be less than half of your intensity settings for cn/2 (it depends on how much RAM your GPU card has.)

You should check out MoneroOcean's meta-miner, it has the ability to restart miners if they don't submit shares in X amount of time.

**Comment by tinsami1** [comment]
old Issue... closing... newer version do not exhibit this problem.
